### ISSUE TITLE
Aligning CSS property values

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/technologies#92]
### What you would like to change/add
Within the recently PR attempting to push through some stylesheet styleguides (#91) it was raised that at least one person likes to not align values. So let's vote 🇬🇧 

### Why you would like to change/add this
Within the styleguide I put that property variables should be aligned.

##### Not aligned
```css
.button {
    background-color: red;
    text-transform: capitalize;
    color: blue;
}
```
##### Aligned
```css
.button {
    background-color: red;
    text-transform:   capitalize;
    color:            blue;
}
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

### How to vote

👍 Aligning values
👎 Not aligning values

**Comment by JacobBrassington** [comment]
What are peoples thoughts on aligning on colon rather than value, something like this?
```css
.button {
    background-color: red;
    text-transform      : capitalize;
    color                      : blue;
}
```
